apiVersion: apps/v1
kind: Deployment
metadata:
name: simple-node
labels:
app: simple-node
spec:
replicas: 2
selector:
matchLabels:
app: simple-node
template:
labels:
app: simple-node
spec:
containers:
-name: simple-node
image:
ports:
-containersPort: 80